#!/bin/bash
#
# Usage: git-credential-ghtoken <operation>
#
# Allows `git` to authenticate with GitHub using `GH_USER` and `GH_TOKEN`
# environment variables.
#
# To install this:
#
#     git config --global credential.https://github.com.helper \
#         "$(pwd)/scripts/git-credential-ghtoken"
#
# Or copy it into your path and run:
#
#     git config --global credential.https://github.com.helper ghtoken
#
set -euo pipefail

# Parse our command-line arguments.
operation="$1"

# Ignore all operations besides `get`.
if [ "$operation" != get ]; then
    exit 0
fi

# Quit now if we don't have the necessary environment variables.
if [ ! -v GH_USER ] || [ ! -v GH_TOKEN ]; then
    exit 0
fi

# Parse the input we receive from `git`.
while read line; do
    var="$(echo "$line" | sed 's/=.*$//')"
    val="$(echo "$line" | sed 's/^.*=//')"
    case "$var" in
        # Only send credentials over HTTPS.
        protocol)
            if [ "$val" != https ]; then
                exit 0
            fi
            ;;
        # Only send credentials to GitHub (just extra paranoia; change as
        # needed).
        host)
            if [ "$val" != github.com ]; then
                exit 0
            fi
            ;;
    esac
done

# Output our credentials.
cat <<EOD
username=$GH_USER
password=$GH_TOKEN
EOD
